"""
report.py
Generates a standalone HTML report for an OSINT recon run, styled to match
the rest of the portfolio's terminal aesthetic.
"""
import os
import datetime

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>OSINT Recon Report :: {domain}</title>
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600;800&display=swap" rel="stylesheet">
<style>
  :root {{ --bg:#060a07; --panel:#0b120d; --border:#1c3322; --green:#39ff88; --dim:#6f9c81; --text:#d5f5e0; }}
  * {{ box-sizing:border-box; }}
  body {{ background:var(--bg); color:var(--text); font-family:'JetBrains Mono',monospace; padding:32px; max-width:900px; margin:0 auto; }}
  h1 {{ color:var(--green); font-size:22px; }}
  .meta {{ color:var(--dim); font-size:13px; margin-bottom:24px; }}
  .panel {{ background:var(--panel); border:1px solid var(--border); border-radius:4px; padding:16px; margin-bottom:20px; }}
  .panel h3 {{ color:var(--green); margin-top:0; font-size:14px; }}
  table {{ width:100%; border-collapse:collapse; font-size:13px; }}
  td {{ padding:6px 4px; border-bottom:1px solid rgba(28,51,34,0.5); }}
  .sub-list {{ columns:2; font-size:13px; }}
  .footer {{ color:var(--dim); font-size:11px; margin-top:24px; }}
</style>
</head>
<body>
  <h1>&gt; osint_recon_report.log</h1>
  <div class="meta">target: {domain} &nbsp;·&nbsp; generated_at: {generated_at}</div>

  <div class="panel">
    <h3>dns_records</h3>
    <table>{dns_rows}</table>
  </div>

  <div class="panel">
    <h3>rdap_registry_data</h3>
    <table>{rdap_rows}</table>
  </div>

  <div class="panel">
    <h3>subdomains ({sub_count} found via certificate transparency)</h3>
    <div class="sub-list">{sub_list}</div>
  </div>

  <div class="panel">
    <h3>recon_files</h3>
    <table>{files_rows}</table>
  </div>

  <div class="footer">Generated by OSINT Recon Tool · passive/public data only</div>
</body>
</html>
"""


def generate_html_report(domain, addresses, rdap, subdomains, recon_files, out_dir=None):
    out_dir = out_dir or os.path.join(os.path.dirname(__file__), "..", "reports")
    os.makedirs(out_dir, exist_ok=True)

    dns_rows = "".join(f"<tr><td>A</td><td>{ip}</td></tr>" for ip in addresses) or "<tr><td colspan=2>No records resolved</td></tr>"

    if "error" in rdap:
        rdap_rows = f"<tr><td colspan=2>{rdap['error']}</td></tr>"
    else:
        rdap_rows = "".join(
            f"<tr><td>{k}</td><td>{', '.join(v) if isinstance(v, list) else (v or '-')}</td></tr>"
            for k, v in rdap.items()
        )

    sub_list = "<br>".join(subdomains) if subdomains else "none found"
    files_rows = "".join(f"<tr><td>{k}</td><td>{v[:200]}</td></tr>" for k, v in recon_files.items()) or "<tr><td colspan=2>None found</td></tr>"

    html = TEMPLATE.format(
        domain=domain, generated_at=datetime.datetime.now().isoformat(),
        dns_rows=dns_rows, rdap_rows=rdap_rows, sub_count=len(subdomains),
        sub_list=sub_list, files_rows=files_rows,
    )

    path = os.path.join(out_dir, f"osint_{domain.replace('.', '_')}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.html")
    with open(path, "w") as f:
        f.write(html)
    return path
